---
layout:     post
title:      "Weekly 095"
subtitle:   "Algorithm: ; Review: Error Handling; Tips: ; Share: Zeller's congruence"
thumbnail-img: ""
date:       2024-07-13 18:00
author:     "dreamume"
tags: 		[it]
category:   it
---
<head>
    <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {
            skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
            inlineMath: [['$','$']]
            }
        });
    </script>
</head>

# Table of Contents

1.  [Algorithm](#orgd37df22)
2.  [Review](#org13817c9)
    1.  [表达并抛出错误](#org83ffc01)
    2.  [处理错误](#orgbe67fc4)
    3.  [使用抛出函数广播错误](#orgc9a9b5c)
    4.  [使用 Do-Catch 处理错误](#org71c61d9)
    5.  [转换错误为可选值](#org816e6f2)
    6.  [禁止错误广播](#org2219182)
    7.  [指定错误类型](#orgc8e505c)
    8.  [指定清理行为](#org4197bfc)
3.  [Tips](#org56591f9)
4.  [Share](#orgdf15ca4)
    1.  [公式](#orge0484e9)
    2.  [分析](#org7a52dae)


<a id="orgd37df22"></a>

# Algorithm


<a id="org13817c9"></a>

# Review

[Error Handling](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/errorhandling)

错误处理是在你的程序中响应进程和从错误条件中恢复。Swift 提供第一手类支持在运行时抛、捕获、广播和操作可恢复错误

一些操作不保证总是完成执行或产生一个有用的输出。可选项用来表达值的缺失，但当一个操作失败，它通常用来理解什么引起的错误，这样你的代码可相应地做出反应

作为一个例子，考虑一个从磁盘文件中读并处理数据的任务。有很多情况可导致任务失败，包括文件在指定路径下不存在，文件没有读取权限或文件没有用兼容的格式编码。区分这些不同的情形允许程序解决一些错误并通知用户它不能解决的错误


<a id="org83ffc01"></a>

## 表达并抛出错误

在 Swift 中，错误被表示为服从 Error 协议的值类型。这个空协议表示一个类型可被用于错误处理

Swift 枚举是特别适合模型一组相关错误条件，关联值允许描述错误的额外信息。例如，这里显示在一个游戏中操作一个向量机器的错误条件：

    enum VendingMachineError: Error {
        case invalidSelection
        case insufficientFunds(coinsNeeded: Int)
        case outOfStack
    }

抛出一个错误让你显示一些不期望发生的事情并且正常执行流不能继续。你使用 throw 表达式来抛出一个错误。例如，下面代码抛出一个错误显示向量机需要 5 个额外的硬币

    throw VendingMachineError.insufficientFunds(coinsNeeded: 5)


<a id="orgbe67fc4"></a>

## 处理错误

当一个错误抛出，一些代码必须响应来处理错误 - 例如，通过修正问题，尝试一个替代的处理，或通知用户失败

在 Swift 中有 4 种方法处理错误。你可广播一个函数的错误到调用该函数的函数中，用 do-catch 表达式处理错误，把错误作为一个可选值处理，或断言错误不会发生

当一个函数抛出一个错误，它改变了你的程序执行流，这样快速确认你的代码可抛出错误的地方是很重要的。为确定代码中的位置，用 try 关键字或 try? 或 try! 变种 - 在一段代码之前调用一个可抛出错误的函数、方法或初始化方法


<a id="orgc9a9b5c"></a>

## 使用抛出函数广播错误

为表示一个函数、方法或初始化函数可抛出一个错误，要在函数定义的参数之后写 throws 关键字。一个用 throws 标注的函数被称为一个抛出函数。如果函数指定一个特殊的返回类型，throws 关键字要在返回箭头之前

    func canThrowErrors() throws -> String
    func cannotThrowErrors() -> String

下面这个例子，VendingMachine 类有一个 vend(itemNamed:) 方法抛出一个适合的 VendingMachineError 如果请求项目无效，售罄或成本超过当前存款总额：

    struct Item {
        var price: Int
        var count: Int
    }
    
    
    class VendingMachine {
        var inventory = [
            "Candy Bar": Item(price: 12, count: 7),
            "Chips": Item(price: 10, count: 4),
            "Pretzels": Item(price: 7, count: 11)
        ]
        var coinsDeposited = 0
    
    
        func vend(itemNamed name: String) throws {
            guard let item = inventory[name] else {
                throw VendingMachineError.invalidSelection
            }
    
    
            guard item.count > 0 else {
                throw VendingMachineError.outOfStock
            }
    
    
            guard item.price <= coinsDeposited else {
                throw VendingMachineError.insufficientFunds(coinsNeeded: item.price - coinsDeposited)
            }
    
    
            coinsDeposited -= item.price
    
    
            var newItem = item
            newItem.count -= 1
            inventory[name] = newItem
    
    
            print("Dispensing \(name)")
        }
    }

因为 vend(itemNamed:) 方法广播它抛出的任何错误，调用这个方法的任何代码必须要么处理错误 - 使用一个 do-catch 表达式，try? 或 try! - 或继续广播它们。例如，下面例子中的 buyFavoriteSnack(person:vendingMachine:) 也是一个抛出函数，vend(itemNamed:) 方法抛出的任何错误将广播到 buyFavoriteSnack(person:vendingMachine:) 函数调用它的地方

    let favoriteSnacks = [
        "Alice": "Chips",
        "Bob": "Licorice",
        "Eve": "Pretzels",
    ]
    func buyFavoriteSnack(person: String, vendingMachine: VendingMachine) throws {
        let snackName = favoriteSnacks[person] ?? "Candy Bar"
        try vendingMachine.vend(itemNamed: snackName)
    }

可抛出初始化函数可广播如同抛出函数一样的错误。例如，下面例子中 PurchasedSnack 结构的初始化函数调用一个可抛出函数，且它处理广播到它调用者的任意错误

    struct PurchasedSnack {
        let name: String
        init(name: String, vendingMachine: VendingMachine) throws {
            try vendingMachine.vend(itemNamed: name)
            self.name = name
        }
    }


<a id="org71c61d9"></a>

## 使用 Do-Catch 处理错误

通过运行一段代码你可使用 do-catch 表达式来处理错误。如果一个错误在 do 语句范围内被抛出，它会被对应的 catch 语句匹配并处理

下面是 do-catch 表达式的一般形式

    do {
        try <#expression#>
        <#statements#>
    } catch <#pattern 1#> {
        <#statements#>
    } catch <#pattern 2#> where <#condition#> {
        <#statements#>
    } catch <#pattern 3#>, <#pattern 4#> where <#condition#> {
        <#statements#>
    } catch {
        <#statements#>
    }

catch 不需要处理每个可能抛出的错误。如果没有对应的 catch 处理错误，错误广播到周围的代码。然而，广播的错误必须被某个周围的代码处理。在一个非抛出函数，一个 do-catch 表达式必须处理错误。在一个抛出函数，要么 do-catch 表达式处理了错误或调用函数必须处理错误。如果错误广播到顶层而没有被处理，你会得到一个运行时错误

示例代码如下：

    func nourish(with item: String) throws {
        do {
            try vendingMachine.vend(itemNamed: item)
        } catch is VendingMachineError {
            print("Couldn't buy that from the vending machine.")
        }
    }
    
    
    do {
        try nourish(with: "Beet-Flavored Chips")
    } catch {
        print("Unexpected non-vending-machine-related error: \(error)")
    }
    // Prints "Couldn't buy that from the vending machine."


<a id="org816e6f2"></a>

## 转换错误为可选值

你可以使用 try? 通过转换为一个可选值处理错误。如果一个错误在 try? 表达式中被抛出，表达式的值为 nil。例如，下面代码中 x 和 y 有相同的值和行为

    func someThrowingFunction() throws -> Int {
        // ...
    }
    
    
    let x = try? someThrowingFunction()
    
    
    let y: Int?
    do {
        y = try someThrowingFunction()
    } catch {
        y = nil
    }

当你想要以相同的方式处理所有错误时使用 try? 让你写出健壮的错误处理代码。例如下面的代码：

    func fetchData() -> Data? {
        if let data = try? fetchDataFromDisk() { return data }
        if let data = try? fetchDataFromServer() { return data }
        return nil
    }


<a id="org2219182"></a>

## 禁止错误广播

有时你知道一个抛出函数或方法事实上不会在运行时抛出错误。在这种情况下，你可写 try! 禁止错误广播并封装调用在运行时断言中表示没有错误将会抛出。如果一个错误被抛出，你将得到一个运行时错误

示例如下

    let photo = try! loadImage(atPath: "./Resources/John Appleseed.jpg")


<a id="orgc8e505c"></a>

## 指定错误类型

上述所有的例子使用最常见的错误处理，代码中抛出的错误可为服从 Error 协议的任意类型值。这个处理符合当代码运行时实际上你不能提前知道每个发生的错误，特别当从其他地方广播的错误。它也反映事实即错误可在任何时间变化。一个库的新版本 - 包含你依赖使用的库 - 可抛出新的错误，且实际中用户配置的广大复杂度可暴露失败模式在开发或测试时不可见。上述例子中的错误处理代码总是包含一个缺省的例子来处理错误不需要一个特别的 catch 语句

大多数 Swift 代码不指明抛出错误的类型。然而，在下面特别的情况下你可限制代码只抛出一个特别的错误类型：

-   当在一个嵌入式系统上运行代码不支持动态分配内存。抛出任意 Error 或其他封装协议类型的实例需要在运行时分配内存存储错误。相反的，抛出一个特定类型的错误使得 Swift 避免对错误进行堆分配
-   当一个错误是某个代码单位实现细节，比如一个库，且不是代码接口的部分。因为错误只来自于库，且不是从其他依赖或库的客户端代码，你可制作一个所有可能失败的全面列表。且因为这些错误是库的实现细节，总是在库里处理
-   只广播被一般性参数描述的错误的代码，比如一个函数带一个闭包参数和广播该闭包的任意错误

例如，考虑代码总结评价和使用以下错误类型

    enum StatisticsError: Error {
        case noRatings
        case invalidRating(Int)
    }

为指定一个函数只抛出 StatisticsError 值作为错误，你在定义函数时写 throws(StatisticsError)。这个语法也称为类型抛出。例如，下面函数抛出 StatisticsError 值作为它的错误

    func summarize(_ ratings: [Int]) throws(StatisticsError) {
        guard !ratings.isEmpty else { throw .noRatings }
    
    
        var counts = [1: 0, 2: 0, 3: 0]
        for rating in ratings {
            guard rating > 0 && rating <= 3 else { throw .invalidRating(rating) }
            counts[rating]! += 1
        }
    
    
        print("*", counts[1]!, "-- **", counts[2]!, "-- ***", counts[3]!)
    }

你可在一个常规抛出函数中调用一个使用类型抛出的函数

    func someThrowingFunction() -> throws {
        let ratings = [1, 2, 3, 2, 2, 1]
        try summarize(ratings)
    }

其等同于

    func someThrowingFunction() -> throws(any Error) {
        let ratings = [1, 2, 3, 2, 2, 1]
        try summarize(ratings)
    }

你可写一个函数不会抛出错误用 throws(Never)

    func nonThrowingFunction() throws(Never) {
      // ...
    }

你也可在 do-catch 表达式中指明错误类型

    let ratings = []
    do throws(StatisticsError) {
        try summarize(ratings)
    } catch {
        switch error {
        case .noRatings:
            print("No ratings available")
        case .invalidRating(let rating):
            print("Invalid rating: \(rating)")
        }
    }
    // Prints "No ratings available"


<a id="org4197bfc"></a>

## 指定清理行为

使用一个 defer 表达式执行一系列行为在代码离开当前代码块之前。这个表述让你做任意清理处理不管代码如何执行离开当前代码块 - 是否它离开因为抛出了一个错误或因为 return 或 break 导致

多个 defer 表述以相反的顺序执行，即第一个 defer 表述会最后执行

    func processFile(filename: String) throws {
        if exists(filename) {
            let file = open(filename)
            defer {
                close(file)
            }
            while let line = try file.readline() {
                // Work with the file.
            }
            // close(file) is called here, at the end of the scope.
        }
    }


<a id="org56591f9"></a>

# Tips


<a id="orgdf15ca4"></a>

# Share

[Zeller's congruence](https://en.wikipedia.org/wiki/Zeller%27s_congruence)

Zeller 的同构是 Christian Zeller 在 19 世纪发明的算法计算儒略历或公历日期对应的周几。它基于儒略历和公历日期的转换


<a id="orge0484e9"></a>

## 公式

对公历，Zeller 的同构为

$ h = \\\left( q + \\&lfloor; \\\frac{13(m+1)}{5} \\&rfloor; + K + \\&lfloor; \\\frac{K}{4} \\&rfloor; + \\&lfloor; \\\frac{J}{4} \\&rfloor; - 2J \\\right) \\\bmod 7 $

对儒略历为

$ h = \\\left( q + \\&lfloor; \\\frac{13(m+1)}{5} \\&rfloor; + K + \\&lfloor; \\\frac{K}{4} \\&rfloor; + 5 - J \\\right) \\\bmod 7 $

-   h 是周几（0 = 周六，1 = 周日，2 = 周一, &#x2026;, 6 = 周五）
-   q 是月份中的日期
-   m 是月份（3 = 三月，4 = 四月, &#x2026;, 14 = 二月）
-   K 是年份对 100 求余
-   J 是年份除以 100 取下限
-   $ \\&lfloor; \\\ldots \\\rfllor $ 是整数取下限
-   mod 是求余操作

注意在这个算法中一月和二月被作为前一年的第 13 和 14 月。例如，2010 年 2 月 2 号，算法会视为 2009 年第 14 月第 2 天

对 ISO 周日期（1 = 周一到 7 = 周日），使用

$ d = \\$ \\( h + 5 \$ \\\bmod 7\\\\) + 1 $


<a id="org7a52dae"></a>

## 分析

这些公式基于在基于日期的每个子部分的预测方法上周日期的观察。公式的每项用于计算需要获得获得正确周日期的偏移

对公历，这个公式的各个部分因此理解如下：

-   q 代表基于月份上天数的周日期，因为每个持续日结果在周日期上有一个额外的 1 的偏移
-   K 代表基于年份的周的日期的处理。假设每年是 365 天，每个后续年的相同日期上将有一个 365 mod 7 = 1 的偏移
-   因为每个闰年有 366 天，这需要通过在周的日期上加一个 1 天的偏移值。这通过添加 $ \\&lfloor; \\\frac{K}{4} \\&rfloor; $ 的偏移实现
-   使用相似的逻辑，对每个世纪周日期的处理通过观察在正常的世纪里有 36524 天和每个能被 400 整除的世纪里有 36525 天。因为 36525 mod 7 = 6 和 36524 mod 7 = 5，$ \\&lfloor; \\\frac{J}{4} \\&rfloor; - 2 J $ 就是计算的这个
-   项目 $ \\&lfloor; \\\frac{13(m+1)}{5} \\&rfloor; $ 为月份中天数的变种。从一月开始，每月的天数为 31, 28/29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31。二月比较特殊，所以公式把一月和二月移到末尾这样二月的短缺就不会引起问题。公式要求周几，这样序列中的数可对 7 取模。这样每月天数对 7 取模后的值为 3，0/1, 3, 2, 3, 2, 3, 3, 2, 3, 2, 3。从三月开始，序列交替为 3, 2, 3, 2, 3，但每 5 月有 2 个 31 天数的月份。分数 13/5 = 2.6 且取下值函数起了作用；除数 5 使得 5 月作为一个周期
-   整个函数对 7 取模，即为每周对应的日期

不同日历间公式的不同是因为儒略历对润世纪没有独立的规则，且是通过每个世纪固定的天数从公历计算偏移

